package com.sergiocrespotoubes.mvpdagger2retrofitroomrxjava.ui.root;


import android.support.v4.app.Fragment;

/**
 * Developed by SergioCT
 * <p>
 * www.SergioCrespoToubes.com
 * https://github.com/Sergioct
 * <p>
 * Code autogenerated.
 */

public class BaseFragment extends Fragment {

}