package com.sergiocrespotoubes.mvpdagger2retrofitroomrxjava.ui.root;

import android.app.Activity;

/**
 * Developed by SergioCT
 * <p>
 * www.SergioCrespoToubes.com
 * https://github.com/Sergioct
 * <p>
 * Code autogenerated.
 */

public class BaseActivity extends Activity implements BaseContract.View {

}